### ISSUE TITLE
Differences between compressed images vs recreating the corrupted dataset

### ISSUE THREAD

**Issue by EvgeniaAR** [hendrycks/robustness#16]
Hi there,

I notice considerable differences in accuracy for Tiny-ImageNet when using the provided JPEGs vs recreating the corrupted dataset with the function make_tinyimagenet_c.py. I have run make_tinyimagenet_c.py for the validation dataset of Tiny ImageNet and tested the accuracy of a trained model on Gaussian noise. For the compressed images and severity=3, I get an accuracy of around 20%, and if I recreate the dataset, the accuracy is around 31%. Since recreating the dataset saves the new corrupted images as JPEGs, the compression should not be the issue.

I am using a resnet-18 for my evaluation.

Do you know how that might happen?

**Comment by hendrycks** [comment]
The reason for using JPEGs (with low compression) is so that evaluation is deterministic, consistent across platforms, and does not require installing libraries. For 224x224x3 images, if I recall correctly, the accuracy hit by JPEG compression was only a few percent on average. I'll make a note in the README that using the JPEGs are suggested. Thanks!

**Comment by ArneNx** [comment]
Hi all, 
I see the same problem when evaluating on Tiny-ImageNet-C (~10% performance loss for takin the given JPEGs vs generated noise). For CIFAR-C this doesn't happen (which would point to JPEG as the cause).
If I understand you correctly, you're saying the JPEG compression should not cause this. Is there any new insight into what may cause this?  (Maybe @EvgeniaAR found something?)

**Comment by hendrycks** [comment]
It's possible that on smaller images, JPEG makes the distribution shift even harder, and I don't see this as much of a problem.

**Comment by ArneNx** [comment]
It's just that my results for Tiny-ImageNet-C look very different from CIFAR100-C and CIFAR10-C. So because of this issue here, I'm not sure if I can really trust the TinyImageNet-C results. Do you have any experience regarding the consistency across those different settings? 
In general, I think I have to wait for my ImageNet results to really draw any conclusions.

**Comment by hendrycks** [comment]
Tiny ImageNet-C should be much more indicative of ImageNet-C performance
than CIFAR-10-C.
