### ISSUE TITLE
Test inception v3 model

### ISSUE THREAD

**Issue by EvgeniaAR** [hendrycks/robustness#17]
Is there a reason why the imagenet c inception dataset (3x299x299) is available on the Google drive, but no inception model is available in the test.py function? Would it be possible to include it? :)

**Comment by hendrycks** [comment]
Hi,

I did not put it in the test.py file because ImageNet-C results on 3x299x299 images are not comparable to results on 3x224x224 images. 3x224x224 is more common in research. However, evaluating performance on Inception should be as simple as importing a model using https://github.com/Cadene/pretrained-models.pytorch
