### ISSUE TITLE
Tiny-Imagenet-c original set without corruptions

### ISSUE THREAD

**Issue by abhijay-g** [hendrycks/robustness#39]
Hi,

Where can I find Tiny Imagenet-C images without any corruption?

**Comment by hendrycks** [comment]
The train images are here: https://tiny-imagenet.herokuapp.com/
This might also be what you're looking for: https://drive.google.com/file/d/1pTkzhONG8o2Zx9ocYqjmqY3G5ejtzFjr/view?usp=sharing

**Comment by zwxu064** [comment]
https://tiny-imagenet.herokuapp.com/ is not accessible, while this tinyimagenet-c is different from http://cs231n.stanford.edu/tiny-imagenet-200.zip (I checked the test images, same index images have different objects).
Where did you get the original tinyimagenet (without corruption)? Thanks.

**Comment by zwxu064** [comment]
> Hi,
> 
> Where can I find Tiny Imagenet-C images without any corruption?

Could you please share me with this dataset?

**Comment by zwxu064** [comment]
> The train images are here: https://tiny-imagenet.herokuapp.com/
> This might also be what you're looking for: https://drive.google.com/file/d/1pTkzhONG8o2Zx9ocYqjmqY3G5ejtzFjr/view?usp=sharing

https://tiny-imagenet.herokuapp.com/ is not accessible, while this tinyimagenet-c is different from http://cs231n.stanford.edu/tiny-imagenet-200.zip (I checked the test images, same index images have different objects).
Where did you get the original tinyimagenet (without corruption)? Thanks.

**Comment by hendrycks** [comment]
We repeated the data generating process of Tiny ImageNet (with the same bounding box crop procedure), resized to 64x64, applied the corruption, then saved with JPEG. There is not a direct match between Tiny ImageNet test images and Tiny ImageNet-C test images, and Tiny ImageNet-C images do not overlap with Tiny ImageNet training images.
This is different from what people might first expect. One might expect us to take the original 64x64 Tiny ImageNet test JPEGs, apply the corruption, and compress them again with JPEG. We did not do this because it would apply two rounds of compression to these small 64x64 images.
Here are the images:
https://drive.google.com/file/d/1pTkzhONG8o2Zx9ocYqjmqY3G5ejtzFjr/view?usp=sharing
